### ISSUE TITLE
Som en bruker med lav rating vil jeg tjene mer rating om jeg slår en som har høy rating

### ISSUE THREAD

**Issue by koderjohannes** [itverket/competify#1]
Hvis en bruker som har 2000 rating og en annen bruker som har 1000 rating spiller mot hverandre, burde ratingen man mister/tjener skaleres ut i fra ratingen man har. Man burde tjene mer rating om man slår en med høyere rating enn seg selv, og man burde tjene mindre om man slår en med lavere rating enn seg selv.

Denne typen skalering åpner også for at folk som ikke er på kontoret hver dag og spiller dag inn og dag ut har mulighet til å konkurrere da de har muligheten til å få en skalert inntjening av rating ved å slå en som har høyere rating enn seg selv.

**Comment by kofoedanders** [comment]
Det er sånn ELO-rating fungerer.

**Comment by koderjohannes** [comment]
Perfekt! Kunne du forklart litt om hvordan den skaleres?

**Comment by kofoedanders** [comment]
https://github.com/itverket/competify/blob/main/src/Web/EloCalculator.cs 

Ev finner du mange forklaringer av formlene om du googler. ELO er systemet som brukes av blant andre FIDE (sjakk), i Starcraft og CS:GO
